name: Close Pull Request

on:
  pull_request_target:
    types: [auto_merge_enabled]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "Merged auto merge PR"
