name: Deploy to Production
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit hash'
        required: true
        default: 'HEAD'

jobs:
  deploy_to_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.commit }}

      - name: Print current commit
        run: git status
   