# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  release-new-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure committer
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn release

  deploy:
    environment: test
    needs: release-new-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'yarn'
    - run: yarn deploy
